//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quizAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Table
    {
        public int ID { get; set; }
        public Nullable<int> Quiz_ID { get; set; }
        public Nullable<byte> QuestionNumber { get; set; }
        public string QuestionText { get; set; }
        public string FirstAnswer { get; set; }
        public string SecondAnswer { get; set; }
        public string ThirdAnswer { get; set; }
        public string FourthAnswer { get; set; }
        public Nullable<bool> IsFirstAnswerCorrect { get; set; }
        public Nullable<bool> IsSecondAnswerCorrect { get; set; }
        public Nullable<bool> IsThirdAnswerCorrect { get; set; }
        public Nullable<bool> isFourthAnswerCorrect { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
