//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quizAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jackbenn_BennettoEntities : DbContext
    {
        public jackbenn_BennettoEntities()
            : base("name=jackbenn_BennettoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Table> Account_Table { get; set; }
        public virtual DbSet<Questions_Table> Questions_Table { get; set; }
        public virtual DbSet<Quiz_Table> Quiz_Table { get; set; }
    }
}
